services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity # line ini biar appnya ga jalan, jadi jalanin auto
    # command: ["pnpm", "start:prod"]